<div id="page">
	 <div id="mainContent">
	 <!-- main Content Boxes -->
	  <div class="mainBox">
		<!-- Main Box -->
		 <div class="mainBoxTitle">
		 <h1 class="mainBoxHeader">Privacy Policy</h1>
		 </div>
		 <div id="textBoxInfo">
<h2 class="textBoxSub">Effective and Last Modified: December 31, 2012</h2>
<p>This policy (“Privacy Policy”) informs you of the policies of Salem Communications Corporation and its subsidiary entities (collectively, “Salem”) concerning the collection, use and disclosure of personal information from this and other Salem-related websites (the “Website(s)”).  Because we may gather certain types of information about our users and understand your privacy is important to you, we want to help you understand the terms and conditions surrounding the collection and use of that information.  Even though we may need to collect information about you to provide some of the products and services we offer, you may not want us to disclose that information to others.  Accordingly, what follows is a description of how we gather and use information about you (collectively “Your Information”).  Please read this Privacy Policy carefully so that you understand what information we collect through our Websites, what we do with that information, and how to safeguard personal information you provide to us.</p>
<h2 class="textBoxSub">Disclosure of Personal Information to Outside Parties:</h2>
<p>Except as set forth in this policy, Salem does not sell, trade, or rent your personal information to others.  However, Salem may provide aggregate statistics about our customers, traffic patterns, and related Website information to third-party vendors. Generally, these statistics will include no personally identifying information.  Salem may also release Your Information when we believe, in good faith, that such release is reasonably necessary to (i) comply with the law, (ii) enforce or apply the terms of our Terms of Use applicable to this Website, (iii) enforce contest, sweepstakes, promotions, and/or game rules, or (iv) protect the rights, property or safety of Salem, our users, or others.  Also, we may give some or all of Your Information to third-party vendors who assist us in fulfilling some of the functions of this Website.  Finally, we may provide Your Information to third parties if you authorize us to do so.</p><h2 class="textBoxSub">Information We Collect and How We Use It:</h2>
<p><b>Voluntary Information You Provide Us.</b>  If you contact us by email, complete our registration forms, surveys, or entry forms, subscribe to our services or newsletters or participate in any of our contests or sweepstakes, we will ask you for Your Information.  The information we ask for in this context may include contact information (such as your name and email address) and/or demographic information (such as your zip code or age).  Below you will find descriptions of how Salem may use these types of information.</p>
<h2 class="textBoxSub"> Registration Data</h2>
<p><b>Registration data is voluntary</b> personal information provided directly by you in order to receive optional access to certain services or Website areas and which may include information such as your name, age, email address, zip code or telephone number.  In addition, registration data may include preference information such as usernames, passwords, desired newsletters, etc.  Here are some of the ways we might use Your Information in this context:</p><ul>	<li>To deliver services such as newsletters, offers, message boards, forums and other items;</li>	<li>To help us create and deliver the content that is most relevant to you;</li>	<li>To alert you to news, events, contests, and other items if you so request;</li>	<li>To allow you entrance into restricted areas of the Website, as appropriate;</li>	<li>To send you information about yoursanime and our Websites;</li>	<li>To compile statistics and conduct basic research; and</li>	<li>To give to third parties, who may send you promotional material.</li></ul>
<p><b> Surveys.</b>  Sometimes Salem posts optional surveys in which we ask for Your Information.  The choice is yours – you don’t have to answer surveys, but if you do, please understand that Salem may use Your Information and that we may share Your Information with third parties.  If we’re asking for optional information, we may mark it as such so that you can skip that portion if you would like.  Here are some ways we might use Your Information in this context: </p>
		 </div>
		</div>
		<!-- End Main Box -->
 </div>
	 <!-- End Main Content Boxes -->
{include file="sidebar.tpl"}